name: timelines_plus
description: "Just updated version of Timelines package. Note: this is just updated version of this package: https://pub.dev/packages/timelines "
version: 1.0.7
homepage: https://github.com/sawin0/timelines_plus

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
